apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-demo
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: 'git@github.com:visbltSE/v-argocd-test.git' ################# CHANGE ME
    path: user-demo/deploy/ck8s-user-demo
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
